#!/usr/bin/env bash
cat /dev/null > /var/lib/jparser/devices.txt
rm -f /var/lib/jparser/white_list_data.txt
rm -f /var/lib/jparser/white_list_connections.txt
rm -f /var/lib/jparser/white_list_report.json
rm -f /var/lib/jparser/devices_ip.txt
cat /dev/null > /etc/suricata.d/rules/redpiranha/white_list.rules
rm -f /etc/jparser/count.txt
echo "1100000" > /etc/jparser/count.txt
